const mrtStations = [
  { code: "NS1", mrtName: "Jurong East" },
  { code: "NS2", mrtName: "Bukit Batok" },
  { code: "NS3", mrtName: "Bukit Gombak" },
  { code: "NS4", mrtName: "Choa Chu Kang" },
  { code: "NS5", mrtName: "Yew Tee" },
  { code: "NS7", mrtName: "Kranji" },
  { code: "NS8", mrtName: "Marsiling" },
  { code: "NS9", mrtName: "Woodlands" },
  { code: "NS10", mrtName: "Admiralty" },
  { code: "NS11", mrtName: "Sembawang" },
  { code: "NS12", mrtName: "Canberra" },
  { code: "NS13", mrtName: "Yishun" },
  { code: "NS14", mrtName: "Khatib" },
  { code: "NS15", mrtName: "Yio Chu Kang" },
  { code: "NS16", mrtName: "Ang Mo Kio" },
  { code: "NS17", mrtName: "Bishan" },
  { code: "NS18", mrtName: "Braddell" },
  { code: "NS19", mrtName: "Toa Payoh" },
  { code: "NS20", mrtName: "Novena" },
  { code: "NS21", mrtName: "Newton" },
  { code: "NS22", mrtName: "Orchard" },
  { code: "NS23", mrtName: "Somerset" },
  { code: "NS24", mrtName: "Dhoby Ghaut" },
  { code: "NS25", mrtName: "City Hall" },
  { code: "NS26", mrtName: "Raffles Place" },
  { code: "NS27", mrtName: "Marina Bay" },
  { code: "NS28", mrtName: "Marina South Pier" },
  { code: "EW1", mrtName: "Pasir Ris" },
  { code: "EW2", mrtName: "Tampines" },
  { code: "EW3", mrtName: "Simei" },
  { code: "EW4", mrtName: "Tanah Merah" },
  { code: "EW5", mrtName: "Bedok" },
  { code: "EW6", mrtName: "Kembangan" },
  { code: "EW7", mrtName: "Eunos" },
  { code: "EW8", mrtName: "Paya Lebar" },
  { code: "EW9", mrtName: "Aljunied" },
  { code: "EW10", mrtName: "Kallang" },
  { code: "EW11", mrtName: "Lavender" },
  { code: "EW12", mrtName: "Bugis" },
  { code: "EW13", mrtName: "City Hall" },
  { code: "EW14", mrtName: "Raffles Place" },
  { code: "EW15", mrtName: "Tanjong Pagar" },
  { code: "EW16", mrtName: "Outram Park" },
  { code: "EW17", mrtName: "Tiong Bahru" },
  { code: "EW18", mrtName: "Redhill" },
  { code: "EW19", mrtName: "Queenstown" },
  { code: "EW20", mrtName: "Commonwealth" },
  { code: "EW21", mrtName: "Buona Vista" },
  { code: "EW22", mrtName: "Dover" },
  { code: "EW23", mrtName: "Clementi" },
  { code: "EW24", mrtName: "Jurong East" },
  { code: "EW25", mrtName: "Chinese Garden" },
  { code: "EW26", mrtName: "Lakeside" },
  { code: "EW27", mrtName: "Boon Lay" },
  { code: "EW28", mrtName: "Pioneer" },
  { code: "EW29", mrtName: "Joo Koon" },
  { code: "EW30", mrtName: "Gul Circle" },
  { code: "EW31", mrtName: "Tuas Crescent" },
  { code: "EW32", mrtName: "Tuas West Road" },
  { code: "EW33", mrtName: "Tuas Link" },
  { code: "CG1", mrtName: "Expo" },
  { code: "CG2", mrtName: "Changi Airport" },
  { code: "NE1", mrtName: "HarbourFront" },
  { code: "NE3", mrtName: "Outram Park" },
  { code: "NE4", mrtName: "Chinatown" },
  { code: "NE5", mrtName: "Clarke Quay" },
  { code: "NE6", mrtName: "Dhoby Ghaut" },
  { code: "NE7", mrtName: "Little India" },
  { code: "NE8", mrtName: "Farrer Park" },
  { code: "NE9", mrtName: "Boon Keng" },
  { code: "NE10", mrtName: "Potong Pasir" },
  { code: "NE11", mrtName: "Woodleigh" },
  { code: "NE12", mrtName: "Serangoon" },
  { code: "NE13", mrtName: "Kovan" },
  { code: "NE14", mrtName: "Hougang" },
  { code: "NE15", mrtName: "Buangkok" },
  { code: "NE16", mrtName: "Sengkang" },
  { code: "NE17", mrtName: "Punggol" },
  { code: "CC1", mrtName: "Dhoby Ghaut" },
  { code: "CC2", mrtName: "Bras Basah" },
  { code: "CC3", mrtName: "Esplanade" },
  { code: "CC4", mrtName: "Promenade" },
  { code: "CC5", mrtName: "Nicoll Highway" },
  { code: "CC6", mrtName: "Stadium" },
  { code: "CC7", mrtName: "Mountbatten" },
  { code: "CC8", mrtName: "Dakota" },
  { code: "CC9", mrtName: "Paya Lebar" },
  { code: "CC10", mrtName: "MacPherson" },
  { code: "CC11", mrtName: "Tai Seng" },
  { code: "CC12", mrtName: "Bartley" },
  { code: "CC13", mrtName: "Serangoon" },
  { code: "CC14", mrtName: "Lorong Chuan" },
  { code: "CC15", mrtName: "Bishan" },
  { code: "CC16", mrtName: "Marymount" },
  { code: "CC17", mrtName: "Caldecott" },
  { code: "CC19", mrtName: "Botanic Gardens" },
  { code: "CC20", mrtName: "Farrer Road" },
  { code: "CC21", mrtName: "Holland Village" },
  { code: "CC22", mrtName: "Buona Vista" },
  { code: "CC23", mrtName: "one-north" },
  { code: "CC24", mrtName: "Kent Ridge" },
  { code: "CC25", mrtName: "Haw Par Villa" },
  { code: "CC26", mrtName: "Pasir Panjang" },
  { code: "CC27", mrtName: "Labrador Park" },
  { code: "CC28", mrtName: "Telok Blangah" },
  { code: "CC29", mrtName: "HarbourFront" },
  { code: "CE1", mrtName: "Bayfront" },
  { code: "CE2", mrtName: "Marina Bay" },
  { code: "DT1", mrtName: "Bukit Panjang" },
  { code: "DT2", mrtName: "Cashew" },
  { code: "DT3", mrtName: "Hillview" },
  { code: "DT5", mrtName: "Beauty World" },
  { code: "DT6", mrtName: "King Albert Park" },
  { code: "DT7", mrtName: "Sixth Avenue" },
  { code: "DT8", mrtName: "Tan Kah Kee" },
  { code: "DT9", mrtName: "Botanic Gardens" },
  { code: "DT10", mrtName: "Stevens" },
  { code: "DT11", mrtName: "Newton" },
  { code: "DT12", mrtName: "Little India" },
  { code: "DT13", mrtName: "Rochor" },
  { code: "DT14", mrtName: "Bugis" },
  { code: "DT15", mrtName: "Promenade" },
  { code: "DT16", mrtName: "Bayfront" },
  { code: "DT17", mrtName: "Downtown" },
  { code: "DT18", mrtName: "Telok Ayer" },
  { code: "DT19", mrtName: "Chinatown" },
  { code: "DT20", mrtName: "Fort Canning" },
  { code: "DT21", mrtName: "Bencoolen" },
  { code: "DT22", mrtName: "Jalan Besar" },
  { code: "DT23", mrtName: "Bendemeer" },
  { code: "DT24", mrtName: "Geylang Bahru" },
  { code: "DT25", mrtName: "Mattar" },
  { code: "DT26", mrtName: "MacPherson" },
  { code: "DT27", mrtName: "Ubi" },
  { code: "DT28", mrtName: "Kaki Bukit" },
  { code: "DT29", mrtName: "Bedok North" },
  { code: "DT30", mrtName: "Bedok Reservoir" },
  { code: "DT31", mrtName: "Tampines West" },
  { code: "DT32", mrtName: "Tampines" },
  { code: "DT33", mrtName: "Tampines East" },
  { code: "DT34", mrtName: "Upper Changi" },
  { code: "DT35", mrtName: "Expo" },
  { code: "BP1", mrtName: "Choa Chu Kang" },
  { code: "BP2", mrtName: "South View" },
  { code: "BP3", mrtName: "Keat Hong" },
  { code: "BP4", mrtName: "Teck Whye" },
  { code: "BP5", mrtName: "Phoenix" },
  { code: "BP6", mrtName: "Bukit Panjang" },
  { code: "BP7", mrtName: "Petir" },
  { code: "BP8", mrtName: "Pending" },
  { code: "BP9", mrtName: "Bangkit" },
  { code: "BP10", mrtName: "Fajar" },
  { code: "BP11", mrtName: "Segar" },
  { code: "BP12", mrtName: "Jelapang" },
  { code: "BP13", mrtName: "Senja" },
  { code: "BP14", mrtName: "Ten Mile Junction" },
  { code: "STC", mrtName: "Sengkang" },
  { code: "SE1", mrtName: "Compassvale" },
  { code: "SE2", mrtName: "Rumbia" },
  { code: "SE3", mrtName: "Bakau" },
  { code: "SE4", mrtName: "Kangkar" },
  { code: "SE5", mrtName: "Ranggung" },
  { code: "SW1", mrtName: "Cheng Lim" },
  { code: "SW2", mrtName: "Farmway" },
  { code: "SW3", mrtName: "Kupang" },
  { code: "SW4", mrtName: "Thanggam" },
  { code: "SW5", mrtName: "Fernvale" },
  { code: "SW6", mrtName: "Layar" },
  { code: "SW7", mrtName: "Tongkang" },
  { code: "SW8", mrtName: "Renjong" },
  { code: "PTC", mrtName: "Punggol" },
  { code: "PE1", mrtName: "Cove" },
  { code: "PE2", mrtName: "Meridian" },
  { code: "PE3", mrtName: "Coral Edge" },
  { code: "PE4", mrtName: "Riviera" },
  { code: "PE5", mrtName: "Kadaloor" },
  { code: "PE6", mrtName: "Oasis" },
  { code: "PE7", mrtName: "Damai" },
  { code: "PW1", mrtName: "Sam Kee" },
  { code: "PW2", mrtName: "Teck Lee" },
  { code: "PW3", mrtName: "Punggol Point" },
  { code: "PW4", mrtName: "Samudera" },
  { code: "PW5", mrtName: "Nibong" },
  { code: "PW6", mrtName: "Sumang" },
  { code: "PW7", mrtName: "Soo Teck" },
  { code: "TE1", mrtName: "Woodlands North " },
  { code: "TE2", mrtName: "Woodlands " },
  { code: "TE3", mrtName: "Woodlands South " },
  { code: "TE4", mrtName: "Springleaf" },
  { code: "TE5", mrtName: "Lentor" },
  { code: "TE6", mrtName: "Mayflower" },
  { code: "TE7", mrtName: "Bright Hill" },
  { code: "TE8", mrtName: "Upper Thomson" },
  { code: "TE9", mrtName: "Caldecott" },
  { code: "TE11", mrtName: "Stevens" },
  { code: "TE12", mrtName: "Napier" },
  { code: "TE13", mrtName: "Orchard Boulevard" },
  { code: "TE14", mrtName: "Orchard" },
  { code: "TE15", mrtName: "Great World" },
  { code: "TE16", mrtName: "Havelock" },
  { code: "TE17", mrtName: "Outram Park" },
  { code: "TE18", mrtName: "Maxwell" },
  { code: "TE19", mrtName: "Shenton Way" },
  { code: "TE20", mrtName: "Marina Bay" },
  { code: "TE22", mrtName: "Gardens by the Bay" },
];

export { mrtStations };
